### PR TITLE
add Yama LSM sysctl setting and description

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by lnussel** [comment]
what's the built in default?

I suppose we need a `-` in front to avoid an error message when the setting is not available due to not active lsm

**Comment by dirkmueller** [comment]
@lnussel I had no issue without the value and without "-" in front of it, but I guess it doesn't hurt to set this. Also added the requested information about default value to the description.

**Comment by lnussel** [comment]
ok but yama is not active by default, right? why would you activate it and then have it's main feature disabled then? Seems like the whole point of it is to get the `1` setting.

**Comment by msmeissn** [comment]
@openSUSE/security

**Comment by mgerstner** [comment]
Yes the `1` value is the desired value if you care for hardening. This is kind of a defense in depth measure, if a process running under your user account is compromised it can for example not easily trace other processes owned by the same user account to extract things like passwords other sensitive data.

I asked to enable this in SLE a while ago but it was rejected for fear of compatibility issues. Indeed it is quite a change if you want to debug your system. For example you can no longer use `strace -p $SOME_PID` or `gdb -p $SOME_PID` to attach to running processes. You need to become _root_ for that.

So from a security POV I would certainly favour the `1` setting but it could result in some uproar among power users.

IMHO this is one of the aspects of system configuration that would profit from the explicit selection of a system security profile at installation time and as a system configuration option to allow end users to consciously select a trade-off. Our team proposed such a feature in the past but it wasn't accepted in this form.

**Comment by dirkmueller** [comment]
@lnussel currently, the yama LSM is compiled into the kernel binary (non-module, as it is LSM) but not configured. That's also not usable for anything else than eating memory. 

I have a separate PR open that will initialize yama LSM by default. without this PR, the change would be changing observable user default behavior, which is why I made this PR to reset it to the previous setting and documenting what other options there are. An informed user can opt into a higher level of protection. 

RHEL9 has the same setup (initialized but disabled by default). Ubuntu initializes, but people hate it. Happy to become more secure than RHEL 9 in a follow on commit that the security team can engage in. for now I would like to get the LSM enabled.

**Comment by dirkmueller** [comment]
> IMHO this is one of the aspects of system configuration that would profit from the explicit selection of a system security profile > installation time and as a system configuration option to allow end users to consciously select a trade-off.

This change can be considered a first step into that direction. we could set higher values of ptrace protection when a user opts into it, via e.g. /etc/sysconfig/security

**Comment by dirkmueller** [comment]
> I asked to enable this in SLE a while ago but it was rejected for fear of compatibility issues. Indeed it is quite a change if you want to debug your system

exactly. it should be *possible* to set it (for example if you roll out the openscap SLE hardening measures) but not the default. This is what this PR achieves.

**Comment by dirkmueller** [comment]
Filed https://bugzilla.suse.com/show_bug.cgi?id=1198601 as a followup for hardening SLE.

**Comment by lnussel** [comment]
> @lnussel currently, the yama LSM is compiled into the kernel binary (non-module, as it is LSM) but not configured. That's also not usable for anything else than eating memory.
> 
> I have a separate PR open that will initialize yama LSM by default. without this PR, the change would be changing observable user default behavior, which is why I made this PR to reset it to the previous setting and documenting what other options there are. An informed user can opt into a higher level of protection.

Ah, ok. In that case the change fits better into the picure then :-) Any pointers to the change?

For security profiles we could of course also put settings into different subpackages.

**Comment by dirkmueller** [comment]
> ok. In that case the change fits better into the picure then :-) Any pointers to the change?

https://kerncvs.suse.de/gitweb/?p=kernel-source.git;a=commitdiff;h=5489572878a6ddad53c3b9ac616c1108867f4870

**Pull request merged**
