### PR TITLE
Add enlightenment to the list of window managers

### PR DESCRIPTION
**Pull request by simotek**

### CODE REVIEW

**Comment by dirkmueller** [comment]
Is the wrapping style parseable by yast? I would have expected that this needs to be indented

**Comment by simotek** [comment]
I am unsure, I tried to wrap at approx the same place as other lines in the file, if you would prefer not to wrap it or indent it let me know what is correct as I am still learning.

**Comment by lnussel** [comment]
I think you need to put it on one line. There is only one program that uses the metadata anyways and that is the yast sysconfig editor.

**Comment by simotek** [comment]
ok sure, will resubmit

**Comment by lnussel** [comment]
note you can force push to your branch to update the pull request so you don't have to close it

**Pull request closed without merging**
