### PR TITLE
Remove broken autocompletion overrides and restore default bash behavior

### PR DESCRIPTION
**Pull request by jengelh**
```
$ echo 'main(){}' >x.cpp
$ g++ x.cpp -o y.out
x.cpp:1:1: warning: ISO C++ forbids declaration of ‘main’ with no type [-Wreturn-type]
    1 | main(){}
      | ^~~~
$ gdb y<TAB><TAB>
yacc          yast2         ycpc          youtube-dl    yt-dlp
yast          yat2m         yes           ypdomainname  yzpper
```

The entire completion fluff is broken (inkscape [too](https://bugzilla.suse.com/show_bug.cgi?id=1194549)), so remove this altogether.

### CODE REVIEW

**Comment by lnussel** [comment]
I don't mind reducing complexity. Needs spec file changes too though

**Comment by jengelh** [comment]
So updated. I don't think the Github CI processed it properly though, as "OBS: aaa_base" stays unupdated.

**Comment by lnussel** [comment]
lets try to close and reopen

**Comment by lnussel** [comment]
can't reopen, wtf

**Comment by lnussel** [comment]
2nd try

**Comment by lnussel** [comment]
the button doesnt work, I guess you have to file a new one :(

**Pull request closed without merging**
