### PR TITLE
Add $HOME/.local/bin to PATH, if it exists (bsc#1192248)

### PR DESCRIPTION
**Pull request by juliogonzalez**
Bugzilla link: https://bugzilla.suse.com/show_bug.cgi?id=1192248

Related: https://github.com/rancher-sandbox/rancher-desktop/issues/881

### CODE REVIEW

**Comment by msmeissn** [comment]
your summar should read $HOME not juliogonzalez ;)

**Comment by juliogonzalez** [comment]
> your summar should read $HOME not juliogonzalez ;)

Ooops! :-D

Summary fixed, as well as the commit message.

**Comment by bugfinder** [comment]
can you add this also in files/etc/csh.login line 113 so we have the complete change in one place ? thanks.

**Comment by juliogonzalez** [comment]
> can you add this also in files/etc/csh.login line 113 so we have the complete change in one place ? thanks.

Done!

**Comment by juliogonzalez** [comment]
@bugfinder I guess I will need to prepare the SRs to Basesystem and the Leap 15.X codestreams/SLE codestreams, right?

**Comment by bugfinder** [comment]
the Leap vairants should automatically get this but you have to submit an update for SLE-15 (aaa_base is inherited from SLE-15 for all SPs up to now)

**Comment by juliogonzalez** [comment]
ACK, I will prepare the submission tomorrow.

**Pull request merged**
