### PR TITLE
Some profile fixes

### PR DESCRIPTION
**Pull request by gmbr3**
1) Update MAIL to /var/mail
2) Add VENDOR variable
3) MACHTYPE should use HOSTTYPE

### CODE REVIEW

**Comment by lnussel** [comment]
is MACHTYPE and VENDOR actually used anywhere? I'd probably rather drop them

**Comment by gmbr3** [comment]
> is MACHTYPE and VENDOR actually used anywhere? I'd probably rather drop them

I presume they exist here for non-bash shells. Bash has its own internal copy hence 8cb043fe97c2cf1e4faf3d719f3e562b26b895b6.

**Comment by bitstreamout** [comment]
On 2022/07/25 06:49:42 -0700, Callum Farmer wrote:
> > is MACHTYPE and VENDOR actually used anywhere? I'd probably rather drop them
> 
> I presume they exist here for non-bash shells. Bash has its own internal copy hence 8cb043fe97c2cf1e4faf3d719f3e562b26b895b6. 

Exactly, we had in past several customers which insists that those
are available as well identical for each shell

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by lnussel** [comment]
https://tiswww.case.edu/php/chet/bash/COMPAT

```
15. Bash no longer auto-exports the HOME, PATH, SHELL, TERM, HOSTNAME,
    HOSTTYPE, MACHTYPE, or OSTYPE variables.  If they appear in the initial
    environment, the export attribute will be set, but if bash provides a
    default value, they will remain local to the current shell.
```
So maybe we can remove them for all now?

**Comment by bitstreamout** [comment]
On 2022/07/25 08:11:07 -0700, Ludwig Nussel wrote:
> https://tiswww.case.edu/php/chet/bash/COMPAT
> 
> ```
> 15. Bash no longer auto-exports the HOME, PATH, SHELL, TERM, HOSTNAME,
>     HOSTTYPE, MACHTYPE, or OSTYPE variables.  If they appear in the initial
>     environment, the export attribute will be set, but if bash provides a
>     default value, they will remain local to the current shell.
> ```
> So maybe we can remove them for all now?

Don't please!  I'm not willingly to straighten the triggered bug reports
on the next SLE/ALPS release

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by lnussel** [comment]
The question is whether those issues that may have existed 20 years ago are still there. Bash doesn't export those variables after all and there is quite some effort not using bash for /bin/sh which means those variables won't exist either. Ie no software can really rely on the variables. I wonder how @gmbr3 noticed? :)

**Comment by bitstreamout** [comment]
On 2022/07/26 00:53:33 -0700, Ludwig Nussel wrote:
> The question is whether those issues that may have existed 20 years ago are still there. Bash doesn't export those variables after all and there is quite some effort not using bash for /bin/sh which means those variables won't exist either. Ie no software can really rely on the variables. I wonder how @gmbr3 noticed? :)
> 

My experience is that customers do rely on those variables.
And indeed bash should not modify nor export those variables
... beside TERM variable if it has to be changed.  But a shell
should set missed variables.  This normally does the login process
but in case of an emergency login you want to have those variables
as well.   Beside this I know several customers (e.g. SAP, Huawei)
which expect variables like MACHTYPE.

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Review by bitstreamout — APPROVED** [review]

**Comment by gmbr3** [comment]
> The question is whether those issues that may have existed 20 years ago are still there. Bash doesn't export those variables after all and there is quite some effort not using bash for /bin/sh which means those variables won't exist either. Ie no software can really rely on the variables. I wonder how @gmbr3 noticed? :)

I came to fix the MAIL issue, but since I know how bash handles MACHTYPE subsequently fixed the others.

**Pull request merged**
