### PR TITLE
Add new function xd() "jump to the directory of a file"

### PR DESCRIPTION
**Pull request by mcepl**

### CODE REVIEW

**Comment by bugfinder** [comment]
technically I'm fine with such an alias, Werner and Ludwig, what do you think ?
on the other hand we've been on-par for the different shells, so if we want such a function, shouldn't we also have implementations for ash/csh ?

**Comment by bitstreamout** [comment]
Would be nice to have also for tcsh but tcsh does not have shell functions and the backtick execution can not be inserted into an other backtich execution .... just as an example what is doable:

```
/local/werner> alias xd 'echo `readlink -f \!*`'
/local/werner> xd /etc/hosts
/etc/hosts
```

**Comment by mcepl** [comment]
manpage `dash(1)` seems to indicate that `$()` is supported, but when I run
```sh
$ xd () { cd "$(dirname "$(readlink -f "$1")")" }
>
```
and
```sh
$ xd () { cd "`dirname \`readlink -f "$1"\`` }
>
```
doesn't fare much better. I seem to get dash to some unfinished state. Seems like a function similar to what we have in `/etc/profile.d/alias.ash`, but I am missing something.

**Comment by bitstreamout** [comment]
> manpage `dash(1)` seems to indicate that `$()` is supported, but when I run
> 
> ```shell
> $ xd () { cd "$(dirname "$(readlink -f "$1")")" }
> >
> ```
> 
> and
> 
> ```shell
> $ xd () { cd "`dirname \`readlink -f "$1"\`` }
> >
> ```
> 
> doesn't fare much better. I seem to get dash to some unfinished state. Seems like a function similar to what we have in `/etc/profile.d/alias.ash`, but I am missing something.

Your forgot a semi colon

```
xd () { cd "$(dirname "$(readlink -f "$1")")"; }
```

**Comment by bitstreamout** [comment]
I'm fine with

**Comment by mcepl** [comment]
> I'm fine with

Then check the review, please. Thank you.

**Comment by lnussel** [comment]
Dunno. Do we still add new convenience aliases? I have lots of them in my personal .alias ... :-)

Where would you use this one exactly?
I thought maybe eg "xd soffice" would take me to /usr/lib64/libreoffice/program but one has to specify the full path!?

**Comment by mcepl** [comment]
> Dunno. Do we still add new convenience aliases? I have lots of them in my personal .alias ... :-)
> 
> Where would you use this one exactly?
> I thought maybe eg "xd soffice" would take me to /usr/lib64/libreoffice/program but one has to specify the full path!?

Something like `xd $(grep -r -l 'something' .)`.

**Comment by bitstreamout** [comment]
I suggest for tcsh
```
alias xd 'set d = `readlink -f "\!^"` ; cd "${d:h}"; unset d'
```
that is no dirname command

**Comment by mcepl** [comment]
> that is no dirname command

dirname(1) is in coreutils, isn't it?

**Comment by bitstreamout** [comment]
This is OK for me.

**Pull request merged**
