### PR TITLE
handle /usr/etc/login.defs for wsl

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
needs csh equivalent by someone who knows csh. @bitstreamout ?

**Comment by bitstreamout** [comment]
On 2019/11/06 06:07:46 -0800, Ludwig Nussel wrote:
> needs csh equivalent by someone who knows csh. @bitstreamout ?
> 

foreach logindefs ({,/usr}/etc/login.defs)
    if ( ! -e $logindefs ) continue
    break
end
if ( -e $logindefs ) then
   set _umask_login_defs=`sed -ne 's/^UMASK[[:space:]]*//p' "$logindefs"`
   if ( ${%_umask_login_defs} > 0) then
       umask ${_umask_login_defs}
   endif
   unset _umask_login_defs
endif

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by bitstreamout** [comment]
On 2019/11/06 06:07:21 -0800, Ludwig Nussel wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/openSUSE/aaa_base/pull/65
> 
> -- Commit Summary --
> 
>   * handle /usr/etc/login.defs for wsl
> 
> -- File Changes --
> 
>     M files/etc/profile.d/wsl.sh (28)
> 
> -- Patch Links --
> 
> https://github.com/openSUSE/aaa_base/pull/65.patch
> https://github.com/openSUSE/aaa_base/pull/65.diff

Does not work for e.g. dash

Werner

**Comment by lnussel** [comment]
- [x] bash
- [x] zsh
- [x] dash
- [x] tcsh
- [x] csh

anything else?

**Pull request merged**
