### PR TITLE
No longer install /usr/lib/restricted/bin/hostname => /bin/hostname symlink

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by lnussel** [comment]
Looks ok to me, can't see how this is useful anymore. @bitstreamout do you have any idea what this was used for?

**Comment by bitstreamout** [comment]
Nope, I've no idea? Never used this `/usr/lib/restricted/` path? Could be container stuff, but with a symbolic link?

**Comment by coolo** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=293038

**Comment by coolo** [comment]
It's 15 years, why is everyone forgetting :)

**Comment by coolo** [comment]
(the bug is btw to be REOPENED if we still cared :)

**Comment by lnussel** [comment]
indeed, rbash ends up with normal path

**Comment by bitstreamout** [comment]
On 2022/03/24 03:12:00 -0700, Stephan Kulow wrote:
> It's 15 years, why is everyone forgetting :)

Indeed ... the path then belongs more into the bash package

**Comment by DimStar77** [comment]
```
> zgrep /usr/lib/restricted ARCHIVES.gz 
./x86_64/filesystem-84.87-4.1.x86_64.rpm:    dr-xr-xr-x    2 root     root                        0 Mar  9 19:00 /usr/lib/restricted
./x86_64/filesystem-84.87-4.1.x86_64.rpm:    dr-xr-xr-x    2 root     root                        0 Mar  9 19:00 /usr/lib/restricted/bin
./x86_64/aaa_base-84.87+git20211124.5486aad-1.4.x86_64.rpm:    lrwxrwxrwx    1 root     root                       24 Feb 20 01:02 /usr/lib/restricted/bin/hostname -> ../../../../bin/hostname
```

That's the complete list on Tumbleweed

**Comment by coolo** [comment]
Makes sense

**Comment by dirkmueller** [comment]
you didn't want to do it in the bash package to have more compatibility with non-bash shells ;)

**Comment by bitstreamout** [comment]
rbash is (r)bash

**Comment by dirkmueller** [comment]
@bitstreamout https://bugzilla.opensuse.org/show_bug.cgi?id=293038#c7

**Comment by bitstreamout** [comment]
Then this commit has to be reverted

**Review by dirkmueller — APPROVED** [review]

**Comment by bitstreamout** [comment]
Hmmm
```
/suse/werner> rbash
werner@boole:~> echo $restricted 
false
werner@boole:~> exit
/suse/werner> bash --restricted
werner@boole:~> echo $restricted 
true
werner@boole:~> unset restricted 
bash: unset: restricted: cannot unset: readonly variable
```

**Comment by dirkmueller** [comment]
that only works if called as login shell of course ```# su - restricted
restricted@magnolia:~> echo $restricted
true
```

**Comment by bitstreamout** [comment]
Also bash-complition does trigger error messages like

```/suse/werner> bash --restricted
werner@boole:~> echo $PAbash: /dev/null: restricted: cannot redirect output
bash: _upvars: `-a2': invalid number specifier
bash: /dev/null: restricted: cannot redirect output
bash: _upvars: `-a0': invalid number specifier
```

**Comment by dirkmueller** [comment]
yeah, I don't think bash-completion should work in restricted shells, but thats subject of another discussion ;)

**Comment by DimStar77** [comment]
so, essentially, the entire feature is broken and the presence of 'hostname' as only existing symlink does not really change much about that. 

I'd say we go with that and if that feature is supposed to work, it has to be rebuilt entirely anyway

**Comment by dirkmueller** [comment]
@DimStar77 the feature is working fine, you're removing hostname from the list of defaut-allowed commands, which is harmless (I would fix the dependency but coolo explained to me that you want to strip hostname from default env)

**Pull request merged**
